# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6969268bc2d8a9b2499b2326b41aefddfa89bef1e84bf60d0b77bba6543042a27adea7a23977c39900d3abe4816849bcfcb80d15040d705f8ca85089cedd3219

test:
  secret_key_base: 0f2ead96ecde410b19867d3f7cebe927e008eb0457360c568a5178b465a4d2f837f32951d51ea6d7b76339bbca04871e18f5e69c29a2f3f5d401cf551922fd30

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
