require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SetlistsController do

  # This should return the minimal set of attributes required to create a valid
  # Setlist. As you add validations to Setlist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SetlistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all setlists as @setlists" do
      setlist = Setlist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:setlists).should eq([setlist])
    end
  end

  describe "GET show" do
    it "assigns the requested setlist as @setlist" do
      setlist = Setlist.create! valid_attributes
      get :show, {:id => setlist.to_param}, valid_session
      assigns(:setlist).should eq(setlist)
    end
  end

  describe "GET new" do
    it "assigns a new setlist as @setlist" do
      get :new, {}, valid_session
      assigns(:setlist).should be_a_new(Setlist)
    end
  end

  describe "GET edit" do
    it "assigns the requested setlist as @setlist" do
      setlist = Setlist.create! valid_attributes
      get :edit, {:id => setlist.to_param}, valid_session
      assigns(:setlist).should eq(setlist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Setlist" do
        expect {
          post :create, {:setlist => valid_attributes}, valid_session
        }.to change(Setlist, :count).by(1)
      end

      it "assigns a newly created setlist as @setlist" do
        post :create, {:setlist => valid_attributes}, valid_session
        assigns(:setlist).should be_a(Setlist)
        assigns(:setlist).should be_persisted
      end

      it "redirects to the created setlist" do
        post :create, {:setlist => valid_attributes}, valid_session
        response.should redirect_to(Setlist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved setlist as @setlist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Setlist.any_instance.stub(:save).and_return(false)
        post :create, {:setlist => {  }}, valid_session
        assigns(:setlist).should be_a_new(Setlist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Setlist.any_instance.stub(:save).and_return(false)
        post :create, {:setlist => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested setlist" do
        setlist = Setlist.create! valid_attributes
        # Assuming there are no other setlists in the database, this
        # specifies that the Setlist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Setlist.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => setlist.to_param, :setlist => { "these" => "params" }}, valid_session
      end

      it "assigns the requested setlist as @setlist" do
        setlist = Setlist.create! valid_attributes
        put :update, {:id => setlist.to_param, :setlist => valid_attributes}, valid_session
        assigns(:setlist).should eq(setlist)
      end

      it "redirects to the setlist" do
        setlist = Setlist.create! valid_attributes
        put :update, {:id => setlist.to_param, :setlist => valid_attributes}, valid_session
        response.should redirect_to(setlist)
      end
    end

    describe "with invalid params" do
      it "assigns the setlist as @setlist" do
        setlist = Setlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Setlist.any_instance.stub(:save).and_return(false)
        put :update, {:id => setlist.to_param, :setlist => {  }}, valid_session
        assigns(:setlist).should eq(setlist)
      end

      it "re-renders the 'edit' template" do
        setlist = Setlist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Setlist.any_instance.stub(:save).and_return(false)
        put :update, {:id => setlist.to_param, :setlist => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested setlist" do
      setlist = Setlist.create! valid_attributes
      expect {
        delete :destroy, {:id => setlist.to_param}, valid_session
      }.to change(Setlist, :count).by(-1)
    end

    it "redirects to the setlists list" do
      setlist = Setlist.create! valid_attributes
      delete :destroy, {:id => setlist.to_param}, valid_session
      response.should redirect_to(setlists_url)
    end
  end

end
